# Generated by Django 6.0.5 on 2026-05-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('editorial', models.CharField(blank=True, max_length=200)),
                ('anio_publicacion', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=100)),
                ('cantidad_ejemplares', models.PositiveIntegerField(default=1)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('contraportada', models.ImageField(blank=True, null=True, upload_to='contraportadas/')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('autores', models.ManyToManyField(to='catalogo.autor')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.categoria')),
            ],
            options={
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
    ]
