# Generated by Django 6.0.5 on 2026-05-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS catalogo_editorial (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    nombre VARCHAR(100) NOT NULL
                );
                CREATE TABLE IF NOT EXISTS catalogo_libro_editoriales (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    libro_id INTEGER NOT NULL REFERENCES catalogo_libro(id) DEFERRABLE INITIALLY DEFERRED,
                    editorial_id INTEGER NOT NULL REFERENCES catalogo_editorial(id) DEFERRABLE INITIALLY DEFERRED,
                    UNIQUE(libro_id, editorial_id)
                );
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS catalogo_libro_editoriales;
                DROP TABLE IF EXISTS catalogo_editorial;
            """,
        ),
    ]
