# Generated by Django 4.2.13 on 2026-08-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_autor_id_alter_categoria_id_alter_editorial_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='contraportada',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
