# Generated by Django 4.2.13 on 2026-08-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_libro_contraportada_alter_libro_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='contraportada',
            field=models.FileField(blank=True, null=True, upload_to='contraportadas/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.FileField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
