# Generated by Django 6.0 on 2026-08-14 21:57

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_autor_id_alter_categoria_id_alter_editorial_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='anio_publicacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
