# Generated by Django 6.1.1 on 2026-09-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_libro_anio_publicacion_alter_libro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='topografica',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
