# Generated by Django 6.1.1 on 2026-09-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_libro_topografica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='anio_publicacion',
            new_name='publicacion',
        ),
    ]
