# Generated by Django 6.1.1 on 2026-09-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_coleccion_palabraclave_libro_coleccion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PalabraClave',
            new_name='Etiqueta',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='palabras_clave',
            new_name='etiquetas',
        ),
        migrations.AlterModelOptions(
            name='etiqueta',
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
    ]